name: receive_whatsapp_chat
description: A flutter plugin that enables flutter apps to receive exported chats from WhatsApp.
version: 0.1.2
homepage: https://github.com/dtkdt100/receive_whatsapp_chat

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  path_provider: ^2.0.11
  collection: ^1.16.0
  flutter_archive: ^5.0.0
  receive_sharing_intent: ^1.4.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.whatsapp.receive_whatsapp_chat
        pluginClass: ReceiveWhatsappChatPlugin
      ios:
        pluginClass: ReceiveWhatsappChatPlugin

